const product = [
    { 
        id: "p1",
        model: "camel 12l", 
        category: "គ្រឿងសម្ភារៈក្នុងផ្ទះ", 
        name: "ឆ្នាំងអគ្គិសនី មិនបាច់ប្រើខ្លាញ់",
        price: "46$", 
        photo: "./img/product/camel.png", 
        detail: "ឆ្នាំងអគ្គិសនី សមស្របសម្រាប់ម្ហូបប្រហិត ដោយមិនចាំបាច់ប្រើខ្លាញ់។",
        address: "Phnom Penh",
        phone: "012345678",
    },
    { 
        id: "p2",
        model: "BSP D3", 
        category: "របស់លេង", 
        name: "ដៃហ្គេម",
        price: "23$", 
        photo: "./img/product/d3gr.png", 
        detail: "ដៃហ្គេមគុណភាពខ្ពស់ សម្រាប់កីឡាអេឡិចត្រូនិច។",
        address: "Siem Reap",
        phone: "098765432",
    },
    { 
        id: "p3",
        model: "BSP D3", 
        category: "របស់លេង", 
        name: "ដៃហ្គេម D3 ពណ៌ខ្មៅ",
        price: "23$", 
        photo: "./img/product/d3b.png", 
        detail: "ដៃហ្គេមពណ៌ខ្មៅសម្រាប់កីឡាករ។",
        address: "Battambang",
        phone: "011223344",
    },
    { 
        id: "p4",
        model: "BSP D3", 
        category: "របស់លេង", 
        name: "ដៃហ្គេម D3 ពណ៌ក្រហមខៀវ",
        price: "23$", 
        photo: "./img/product/d3gr.png", 
        detail: "ដៃហ្គេមពណ៌ក្រហមខៀវ ដ៏ស្រស់ស្អាត។",
        address: "Kampot",
        phone: "099887766",
    },
    { 
        id: "p3",
        model: "BSP D3", 
        category: "របស់លេង", 
        name: "ដៃហ្គេម D3 ពណ៌ខ្មៅ",
        price: "23$", 
        photo: "./img/product/d3b.png", 
        detail: "ដៃហ្គេមពណ៌ខ្មៅសម្រាប់កីឡាករ។",
        address: "Battambang",
        phone: "011223344",
    },
    { 
        id: "p4",
        model: "BSP D3", 
        category: "របស់លេង", 
        name: "ដៃហ្គេម D3 ពណ៌ក្រហមខៀវ",
        price: "23$", 
        photo: "./img/product/d3gr.png", 
        detail: "ដៃហ្គេមពណ៌ក្រហមខៀវ ដ៏ស្រស់ស្អាត។",
        address: "Kampot",
        phone: "099887766",
    },
];
